# Generated by Django 5.0.7 on 2024-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
