# Generated by Django 5.0.7 on 2024-11-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0002_advuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Принято в работу'), ('completed', 'Выполнено')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
