# Generated by Django 5.0.7 on 2024-11-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0006_applicationchangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationchangehistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
