# Generated by Django 5.0.7 on 2024-11-13 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0008_remove_applicationchangehistory_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный администратор'),
        ),
    ]
